# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
if [ -f ~/workspace/dotfiles/bash/cmds ]; then
	. ~/workspace/dotfiles/bash/cmds
fi

