#!/bin/bash
ns() {
 _delim="||"
 s=$1$_delim

 _selectioncount=1

 while [[ $s ]]; do
    _selection=${s%%"$_delim"*}

    if [[ $_selection == "" ]]
    then 
	break
    fi

    echo "Selection $_selectioncount [$_selection]"

	IFS='#' read -ra _y <<< "$_selection"
	
	echo -e "\t\033[1;30m## [Construct Section]\033[0;34m"
	for _selectionstring in "${_y[@]}"
	do
		_key=$(echo $_selectionstring | cut -f1 -d=)
		_value=$(echo $_selectionstring | cut -f2 -d=)
	
		if [[ ${_key:0:1} == "|" ]]
		then 
			echo -e "\t\033[1;30m## [User Section]\033[0;34m"
			_key=${_key:1}
		fi

		_lookup_full_selection_name $_key _fullname

		if [[ $_fullname == "" ]]
		then
			printf "\t\033[0;31m %-3s\033[0m = \033[0;34m$_value\033[0m\n" $_key
		else
			 printf "\t\033[0;31m %-3s\033[0;36m($_fullname)\033[0m = \033[0;34m$_value\033[0m\n" $_key
		fi
	done

    	s=${s#*"$_delim"};
   	((_selectioncount++))
	done;
}

_lookup_full_selection_name() {
	local _lookupkey=$1
	local _returnvar=$2
	
	_fullname=${_full_selection_names[$_lookupkey]}	

	if [[ "$_returnvar" ]]; then
		eval $_returnvar="'$_fullname'"
	else
		echo "$_fullname"
	fi
}

declare -A _full_selection_names=(
	["pt"]="Participant Type"
	["f"]="Fixture ID"
	["fp"]="Fixture Participant ID"
	["pid"]="Player Fixture Participant ID"
	["mid"]="Match Fixture Participant ID"
	["o"]="Odds"
	["ln"]="Line / Handicap"
	["sa"]="Selection Added"
	["c"]="Classification ID"
	["oto"]="Odds Type Override"
	["TP"]="Topic Id"
	["ew"]="Each Way"
	["av"]="Auto Void"
	["ust"]="Unit Stake"
	["st"]="Total Stake"
	["fb"]="Free Bet Stake"
	["tr"]="To Return"
	["bk"]="Banker"
	["ft"]="Free Bet Token Id (Redemption)"
	["fbv"]="Free Bet Token value"
)


